# Macro File
# Loops over postion in r, from 0 to 55 mm in 5 mm steps
# Written for two HPGes, coincidence eff
# requires runPos.mac

#turn off visulizer
/vis/disable
#only print ever 10000 events
/TwoCoax/event/printModulo 10000
#Set to manual gun (not gps)
/TwoCoax/gun/rndm off
#set detector distance
#/TwoCoax/det/setDetectorDistance 0.55 cm
#update
#/TwoCoax/det/update
#set position 
/TwoCoax/gun/positionR 55 mm 

#loop over energy values
/control/loop runPos.mac pos 15 55 10 

