# Macro File
# Loops over energy from 300-1500 keV in 100 keV steps
# Designed for a single HPGe
# Requires runEn.mac

#turn off visulizer
/vis/disable
#only print ever 10000 events
/TwoCoax/event/printModulo 10000
#set detector distance
/TwoCoax/det/setDetectorDistance 24.9 cm
#set gun to GPS (general particle source)
/TwoCoax/gun/rndm on
#update
/TwoCoax/det/update

#loop over energy values
/control/loop runEn.mac en 300 1500 100 

